name: 277979481-sync
on:
  schedule:
    - cron: '0 */12 * * *'
  workflow_dispatch:
  watch:
    types: started
  repository_dispatch:
    types: sync-277979481-JDC
jobs:
  repo-sync:
    env:
      PAT: ${{ secrets.PAT }} 
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: sync 277979481-JDC
        uses: repo-sync/github-sync@v2
        if: env.PAT
        with:
          source_repo: "https://github.com/277979481/JDC.git"
          source_branch: "master"
          destination_branch: "277979481"
          github_token: ${{ secrets.PAT }}
