name: panghu999-sync
on:
  schedule:
    - cron: '14 */6 * * *'
  workflow_dispatch:
  watch:
    types: started
  repository_dispatch:
    types: sync-panghu999-ningmeng
jobs:
  repo-sync:
    env:
      PAT: ${{ secrets.PAT }} 
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: sync panghu999-ningmeng
        uses: repo-sync/github-sync@v2
        if: env.PAT
        with:
          source_repo: "https://github.com/panghu999/ningmeng.git"
          source_branch: "main"
          destination_branch: "panghu999n"
          github_token: ${{ secrets.PAT }}
